name: Check Reactor Netty 1.1.x with Reactor Core 3.6 SNAPSHOTS

on:
  schedule:
    - cron: "0 14 * * *"
permissions: read-all
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
        with:
          ref: '1.1.x'
      - name: Set up JDK 1.8
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build with Gradle
        run: ./gradlew clean check --no-daemon -PforceTransport=nio -PreactorCoreVersion='3.6.6-SNAPSHOT' -PforceContextPropagationVersion='1.1.0'
